#...............................................................................
#
#  IO Ninja IAS (In-App Scripting) API for Python
#

from typing import Any

def trace(*values: Any) -> None: ...
def is_connected() -> bool: ...
def connect() -> None: ...
def disconnect() -> None: ...
def transmit(data: bytes) -> int: ...
def get_pending_receive_size() -> int: ...
def receive(size: int, timeout: int = ...) -> bytes: ...
def unreceive(data: bytes) -> None: ...
def write_log(record_code: int, *args: Any) -> None: ...
def clear_log() -> None: ...
